name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm ci --no-audit --no-fund

      - name: Dar permisos de ejecución a Jest
        run: chmod +x node_modules/.bin/jest

      - name: Ejecutar pruebas con npx
        run: npx jest --runInBand

      - name: Ver entorno
        run: |
                echo "Entorno actual: ${{ secrets.NODE_ENV }}"